### ISSUE TITLE
Failure at gdx.read() at Python examples

### ISSUE THREAD

**Issue by duodenum96** [VernierST/godirect-examples#44]
Hello,

While trying to run the gdx_getting_started_usb.py with select_sensor([1]) and start(50) arguments, I get the following error:

Traceback (most recent call last):

  File "C:\Users\user\Desktop\brain_stuff\josh\godirect-examples-main\python\gdx_getting_started_usb.py", line 36, in <module>
    measurements = gdx.read()

  File "C:\Users\user\Desktop\brain_stuff\josh\godirect-examples-main\python\gdx\gdx.py", line 302, in read
    if gdx.devices[i].read():

  File "C:\Users\user\miniconda3\envs\hipokrat\lib\site-packages\godirect\device.py", line 181, in read
    return self._GDX_read_measurement(timeout)

  File "C:\Users\user\miniconda3\envs\hipokrat\lib\site-packages\godirect\device.py", line 401, in _GDX_read_measurement
    return self._GDX_handle_measurement(response)

  File "C:\Users\user\miniconda3\envs\hipokrat\lib\site-packages\godirect\device.py", line 416, in _GDX_handle_measurement
    sensors = self._get_sensors_with_mask(sensor_mask)

  File "C:\Users\user\miniconda3\envs\hipokrat\lib\site-packages\godirect\device.py", line 272, in _get_sensors_with_mask
    sensors[i] = self._sensors[i]

KeyError: 2

Does anyone have any idea related to the reason of this?

**Comment by sswartley** [comment]
Hello,

What happens when you run the example program without adding the arguments to select_sensor() and start()? It should provide you with a list of sensors to choose in the console, as well as allowing you to set the sampling period in the console. Can you choose a single sensor and set the sampling period in the console and run the program without the errror?

Sam
